apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: backend-journal
  name: backend-journal
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service: backend-journal
    spec:
      containers:
      - image: devshack/introspection-restapi-journal
        name: backend-journal
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                     
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true        
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret