
version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: devshack/reverseproxy 
  backend-auth:
    build:
      context: ../../introspection-restapi-auth
    image: devshack/introspection-restapi-auth
  backend-journal:
    build:
      context: ../../introspection-restapi-journal  
    image: devshack/introspection-restapi-journal
  backend-user:
    build:
      context: ../../introspection-restapi-user  
    image: devshack/introspection-restapi-user 